import { createRequire } from "node:module";

const _require = createRequire(import.meta.url);

// ─────────────────────────────────────────────────────────────────────────────
// COMPLETION TREE
//
// ⚠️  每次新增、删除、重命名命令时，必须同步更新此处。
//    同时检查 src/commands/ 下对应文件中的 .command() 声明保持一致。
// ─────────────────────────────────────────────────────────────────────────────
export const COMPLETION_TREE = {
  groups:       ["market", "account", "orders", "bot", "earn", "capabilities"],
  market:       ["depth", "trades", "symbols", "tickers", "book_tickers", "klines"],
  account:      ["balance"],
  orders:       ["new", "get", "open", "all", "fills", "fills_by_order_id", "cancel", "cancel_all"],
  bot:          ["order_list", "futures_grid", "spot_grid", "smart_copy", "signal"],
  futures_grid: ["get", "create", "adjust_params", "reduce", "cancel", "check_params"],
  spot_grid:    ["get", "get_ai_strategy", "create", "adjust_params", "invest_in", "cancel", "profit", "check_params"],
  smart_copy:   ["get", "create", "cancel", "check_params"],
  signal:       ["listener"],
  earn:         ["dual"],
  dual:         ["symbols", "open_products", "prices", "index", "delivery_prices",
                 "balances", "get_invests", "records", "invest", "revoke_invest", "collect"],
} as const;

type OmeletteReply = { reply: (words: readonly string[]) => void };
type OmeletteInstance = {
  on(event: string, handler: (opts: OmeletteReply) => void): void;
  init(): void;
  setupShellInitFile(filepath?: string): void;
  cleanupShellInitFile(filepath?: string): void;
};

/**
 * 初始化 omelette 补全（bash/zsh）。
 * 必须在 commander 解析参数之前调用（模块加载时执行）。
 */
export function initCompletion(): OmeletteInstance {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const omelette = _require("omelette") as (template: string) => OmeletteInstance;
  const completion = omelette("pionex-trade-cli <group> <sub> <cmd>");

  const T = COMPLETION_TREE;
  completion.on("group",        ({ reply }) => reply(T.groups));
  completion.on("market",       ({ reply }) => reply(T.market));
  completion.on("account",      ({ reply }) => reply(T.account));
  completion.on("orders",       ({ reply }) => reply(T.orders));
  completion.on("bot",          ({ reply }) => reply(T.bot));
  completion.on("futures_grid", ({ reply }) => reply(T.futures_grid));
  completion.on("spot_grid",    ({ reply }) => reply(T.spot_grid));
  completion.on("smart_copy",   ({ reply }) => reply(T.smart_copy));
  completion.on("signal",       ({ reply }) => reply(T.signal));
  completion.on("earn",         ({ reply }) => reply(T.earn));
  completion.on("dual",         ({ reply }) => reply(T.dual));

  completion.init();
  return completion;
}

/**
 * 生成 fish shell 补全脚本。
 * 输出到 stdout，用户重定向到：
 *   ~/.config/fish/completions/pionex-trade-cli.fish
 */
export function generateFishCompletion(): string {
  const cmd = "pionex-trade-cli";
  const T = COMPLETION_TREE;
  const lines: string[] = [
    `# ${cmd} fish shell completion`,
    `# Generated by: ${cmd} setup-completion-fish`,
    `# To install:   ${cmd} setup-completion-fish > ~/.config/fish/completions/${cmd}.fish`,
    "",
    "# Disable file completion globally for this command",
    `complete -c ${cmd} -f`,
    "",
    "# Top-level groups",
    ...T.groups.map((g) =>
      `complete -c ${cmd} -n 'not __fish_seen_subcommand_from ${T.groups.join(" ")}' -a '${g}'`
    ),
    "",
    "# market subcommands",
    ...T.market.map((s) => `complete -c ${cmd} -n '__fish_seen_subcommand_from market' -a '${s}'`),
    "",
    "# account subcommands",
    ...T.account.map((s) => `complete -c ${cmd} -n '__fish_seen_subcommand_from account' -a '${s}'`),
    "",
    "# orders subcommands",
    ...T.orders.map((s) => `complete -c ${cmd} -n '__fish_seen_subcommand_from orders' -a '${s}'`),
    "",
    "# bot subcommands (only before entering futures_grid, spot_grid, smart_copy, or signal)",
    ...T.bot.map((s) => `complete -c ${cmd} -n '__fish_seen_subcommand_from bot; and not __fish_seen_subcommand_from futures_grid spot_grid smart_copy signal' -a '${s}'`),
    "",
    "# bot futures_grid commands",
    ...T.futures_grid.map((s) => `complete -c ${cmd} -n '__fish_seen_subcommand_from futures_grid' -a '${s}'`),
    "",
    "# bot spot_grid commands",
    ...T.spot_grid.map((s) => `complete -c ${cmd} -n '__fish_seen_subcommand_from spot_grid' -a '${s}'`),
    "",
    "# bot smart_copy commands",
    ...T.smart_copy.map((s) => `complete -c ${cmd} -n '__fish_seen_subcommand_from smart_copy' -a '${s}'`),
    "",
    "# bot signal commands",
    ...T.signal.map((s) => `complete -c ${cmd} -n '__fish_seen_subcommand_from signal' -a '${s}'`),
    "",
    "# earn subcommands (only before entering dual)",
    ...T.earn.map((s) => `complete -c ${cmd} -n '__fish_seen_subcommand_from earn; and not __fish_seen_subcommand_from dual' -a '${s}'`),
    "",
    "# earn dual commands",
    ...T.dual.map((s) => `complete -c ${cmd} -n '__fish_seen_subcommand_from dual' -a '${s}'`),
    "",
  ];
  return lines.join("\n");
}
